title: AppSec Israel&nbsp;2026
description: OWASP AppSec Israel annual conference - 2026 edition!

year: 2026

address: Tel Aviv Expo, Pavilion 10
# Conference dates
dates:
  conference: May 18, 2026
  cfpCloses: Feb 28, 2026
  notification: coming soon

logoUrl: ./assets/img/2026/AppSecIL_2026_Logo.png

links:
  registration: https://appsecil2026.forms-wizard.biz/
  calendar: https://calendar.google.com/calendar/render?action=TEMPLATE&text=OWASP+AppSec+IL+2026&dates=20260518T060000Z/20260518T150000Z&details=OWASP+AppSec+Israel+is+one+of+the+leading+cybersecurity+conferences+in+the+region,+bringing+together+experts,+professionals,+and+enthusiasts+from+around+the+world.+Join+1,000%2B+developers,+DevOps+engineers,+architects,+security+specialists,+product+leaders,+and+other+industry+professionals+dedicated+to+advancing+the+future+of+application+security.&location=Tel+Aviv+Expo,+Pavilion+10,+Tel+Aviv,+Israel
  cfp: https://sessionize.com/appsecil-2026
