title: AppSec Israel 2023
description: OWASP AppSec Israel annual conference - 2023 edition!

year: 2023

# Conference dates
dates:  May 16th and 17th, 2023
#trainingday: Tuesday, October 27th
#confday: Wednesday, October 28th

sched: owaspappsecil2023.sched.com
